let reservedWords = [
  "abstract",
  "boolean",
  "break",
  "byte",
  "case",
  "catch",
  "char",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "double",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "final",
  "finally",
  "float",
  "for",
  "function",
  "goto",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "int",
  "interface",
  "long",
  "native",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "short",
  "static",
  "super",
  "switch",
  "synchronized",
  "this",
  "throw",
  "throws",
  "transient",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "volatile",
  "while",
  "with",
];
module.exports = function (inputName) {
  if (reservedWords.includes(inputName)) {
    return "Component name cannot be a reserved word";
  }
  let variableNameRegex = /^[A-Za-z_]+[A-Za-z0-9_ ]*$/;
  if (!variableNameRegex.test(inputName)) {
    return "Invalid Component Name";
  }
  return "";
};
